CREATE TABLE stock_details (
   id int NOT NULL AUTO_INCREMENT,
   sembolid int DEFAULT NULL,
   sembol varchar(50) DEFAULT NULL,
   state int DEFAULT NULL,
   increase double DEFAULT NULL,
   tarih datetime DEFAULT NULL,
   sektorid int DEFAULT NULL,
   alis float DEFAULT NULL,
   satis float DEFAULT NULL,
   acilis float DEFAULT NULL,
   yuksek float DEFAULT NULL,
   yukseK1 float DEFAULT NULL,
   yukseK2 float DEFAULT NULL,
   dusuk float DEFAULT NULL,
   dusuK1 float DEFAULT NULL,
   dusuK2 float DEFAULT NULL,
   kapanis float DEFAULT NULL,
   kapaniS1 float DEFAULT NULL,
   kapaniS2 float DEFAULT NULL,
   hacimlot int DEFAULT NULL,
   hacimloT1 int DEFAULT NULL,
   hacimloT2 int DEFAULT NULL,
   aort float DEFAULT NULL,
   aorT1 float DEFAULT NULL,
   aorT2 float DEFAULT NULL,
   hacimtldun mediumtext,
   hacimtl int DEFAULT NULL,
   hacimtL1 int DEFAULT NULL,
   hacimtL2 int DEFAULT NULL,
   hacimyuzdedegisim float DEFAULT NULL,
   dunkukapanis float DEFAULT NULL,
   oncekikapanis float DEFAULT NULL,
   izafikapanis float DEFAULT NULL,
   tavan float DEFAULT NULL,
   taban float DEFAULT NULL,
   yilyuksek float DEFAULT NULL,
   yildusuk float DEFAULT NULL,
   ayyuksek float DEFAULT NULL,
   aydusuk float DEFAULT NULL,
   haftayuksek float DEFAULT NULL,
   haftadusuk float DEFAULT NULL,
   oncekiyilkapanis float DEFAULT NULL,
   oncekiaykapanis float DEFAULT NULL,
   oncekihaftakapanis float DEFAULT NULL,
   yilortalama float DEFAULT NULL,
   ayortalama double DEFAULT NULL,
   haftaortalama double DEFAULT NULL,
   yuzdedegisimS1 float DEFAULT NULL,
   yuzdedegisimS2 float DEFAULT NULL,
   yuzdedegisim float DEFAULT NULL,
   fiyatadimi float DEFAULT NULL,
   kaykar int DEFAULT NULL,
   sermaye mediumtext,
   saklamaor float DEFAULT NULL,
   netkar mediumtext,
   net float DEFAULT NULL,
   fiyatkaz int DEFAULT NULL,
   piydeg mediumtext,
   kapanisfark double DEFAULT NULL,
   donem varchar(100) DEFAULT NULL,
   ozsermaye mediumtext,
   beta double DEFAULT NULL,
   xU100AG varchar(200) DEFAULT NULL,
   aciklama varchar(200) DEFAULT NULL,
   PRIMARY KEY (id),
   KEY sembolid (sembolid),
   FOREIGN KEY (sembolid) REFERENCES companies (id)
 )